main: dev.covector.maplus.MobArenaPlusPlugin
name: MobArenaPlus
version: 1.0
api-version: 1.13
softdepend: [MobArena, ajLeaderboards, MythicMobs, GlowAPI, ProtocolLib, MMOCore, MMOItems]

commands:
   marevive:
      description: Revive random or specified player
      usage: /<command> player [player] OR /<command> random [arena] OR /<command> player [player] [ml skill] OR /<command> random [arena] [ml skill]
   mmability:
      description: Extend mythic mobs abilities by using command interface
      usage: /<command> <ability-id> <arg1> <arg2> <arg3>...
   mlcooldown:
      description: Reset cooldown for mythic lib skill
      usage: /<command>
   tparenamobstoself:
      description: Teleport arena mobs to yourself
      usage: /<command>
   unsocketgems:
      description: Unsocket all gemstones from the MMOItems in hand
      aliases: [unsocket, unsocketgem, unsocketgems, unsocketgemstone, unsocketgemstones]
      usage: /<command>